import type { Profile, PostWithProfile } from "@/lib/supabase/types"
import type { Category, DemoProduct, Achievement, UserAchievement } from "@/lib/types"

// Demo categories (UI display only - not in DB schema)
export const demoCategories: Category[] = [
  { id: "cat-1", name: "AI/ML", slug: "ai", color: "#8B5CF6", icon: "brain" },
  { id: "cat-2", name: "FinTech", slug: "fintech", color: "#10B981", icon: "banknote" },
  { id: "cat-3", name: "AgriTech", slug: "agtech", color: "#22C55E", icon: "leaf" },
  { id: "cat-4", name: "HealthTech", slug: "healthtech", color: "#EF4444", icon: "heart" },
  { id: "cat-5", name: "EdTech", slug: "edtech", color: "#3B82F6", icon: "book" },
  { id: "cat-6", name: "DevTools", slug: "devtools", color: "#F59E0B", icon: "wrench" },
]

// Demo profiles matching Supabase schema
export const demoProfiles: Profile[] = [
  {
    id: "user-1",
    username: "amara_nwosu",
    email: "amara@example.com",
    full_name: "Amara Nwosu",
    avatar_url: "/african-woman-developer.jpg",
    bio: "AI researcher | TechCabal contributor | Building the future of African AI",
    website_url: null,
    github_url: "https://github.com/amara-nwosu",
    twitter_url: "https://twitter.com/amara_nwosu",
    level: 23,
    xp: 2340,
    streak_days: 15,
    last_activity_date: new Date().toISOString(),
    total_posts: 45,
    total_comments: 128,
    helpful_comments: 32,
    total_launches: 2,
    preferred_languages: ["python", "typescript"],
    interests: ["ai", "machine-learning", "african-tech"],
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "user-2",
    username: "kwame_asante",
    email: "kwame@example.com",
    full_name: "Kwame Asante",
    avatar_url: "/african-man-tech.jpg",
    bio: "FinTech founder | Ex-Paystack | Scaling payments across Africa",
    website_url: "https://kwameasante.com",
    github_url: "https://github.com/kwame-asante",
    twitter_url: "https://twitter.com/kwame_asante",
    level: 31,
    xp: 5200,
    streak_days: 42,
    last_activity_date: new Date().toISOString(),
    total_posts: 89,
    total_comments: 234,
    helpful_comments: 67,
    total_launches: 4,
    preferred_languages: ["go", "typescript", "python"],
    interests: ["fintech", "payments", "startups"],
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "user-3",
    username: "fatima_diallo",
    email: "fatima@example.com",
    full_name: "Fatima Diallo",
    avatar_url: "/african-woman-entrepreneur.jpg",
    bio: "AgriTech innovator | Helping farmers with AI-powered solutions",
    website_url: null,
    github_url: null,
    twitter_url: "https://twitter.com/fatima_diallo",
    level: 18,
    xp: 1800,
    streak_days: 8,
    last_activity_date: new Date().toISOString(),
    total_posts: 23,
    total_comments: 67,
    helpful_comments: 19,
    total_launches: 1,
    preferred_languages: ["python", "r"],
    interests: ["agtech", "data-science", "sustainability"],
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "user-4",
    username: "tunde_okonkwo",
    email: "tunde@example.com",
    full_name: "Tunde Okonkwo",
    avatar_url: "/african-man-software-engineer.jpg",
    bio: "Full-stack dev | Open source contributor | Lagos tech community organizer",
    website_url: "https://tunde.dev",
    github_url: "https://github.com/tunde-okonkwo",
    twitter_url: "https://twitter.com/tunde_dev",
    level: 27,
    xp: 3500,
    streak_days: 23,
    last_activity_date: new Date().toISOString(),
    total_posts: 67,
    total_comments: 189,
    helpful_comments: 45,
    total_launches: 3,
    preferred_languages: ["typescript", "rust", "go"],
    interests: ["devtools", "open-source", "web-performance"],
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
]

// Demo posts matching Supabase schema (PostWithProfile)
export const demoPosts: PostWithProfile[] = [
  {
    id: "post-1",
    author_id: "user-1",
    type: "showcase",
    title: "African AI Startups Raise $2.3B in Record Funding Round",
    content:
      "Pan-African AI companies are transforming healthcare, agriculture, and financial services across the continent with innovative machine learning solutions. This marks a turning point for tech investment in Africa.",
    category: "ai",
    tags: ["ai", "funding", "startups", "africa"],
    image_url: "/african-tech-startup-office-team-meeting.jpg",
    upvotes: 1247,
    comment_count: 89,
    view_count: 4520,
    is_answered: false,
    is_featured: true,
    created_at: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
    profiles: demoProfiles[0],
  },
  {
    id: "post-2",
    author_id: "user-2",
    type: "showcase",
    title: "Nigerian FinTech Unicorn Expands to 12 African Countries",
    content:
      "Major expansion announcement as Lagos-based payment platform reaches unicorn status and announces plans to serve 100 million users by 2026.",
    category: "fintech",
    tags: ["fintech", "unicorn", "nigeria", "expansion"],
    image_url: "/mobile-payment-app-africa-fintech.jpg",
    upvotes: 892,
    comment_count: 156,
    view_count: 3200,
    is_answered: false,
    is_featured: true,
    created_at: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
    profiles: demoProfiles[1],
  },
  {
    id: "post-3",
    author_id: "user-3",
    type: "tutorial",
    title: "AI-Powered Crop Disease Detection Saves Millions in Harvest",
    content:
      "New mobile app using computer vision helps smallholder farmers identify crop diseases early, preventing estimated $50M in losses across East Africa.",
    category: "agtech",
    tags: ["agtech", "ai", "agriculture", "mobile"],
    image_url: "/african-farmer-using-smartphone-in-field-agricultu.jpg",
    upvotes: 534,
    comment_count: 67,
    view_count: 1890,
    is_answered: false,
    is_featured: false,
    created_at: new Date(Date.now() - 6 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
    profiles: demoProfiles[2],
  },
  {
    id: "post-4",
    author_id: "user-4",
    type: "discussion",
    title: "Just shipped v2.0 of our open-source ML framework",
    content:
      "Just shipped v2.0 of our open-source ML framework optimized for low-bandwidth environments. 60% smaller model sizes with only 3% accuracy loss. Perfect for African mobile networks! 🚀\n\nCheck it out: github.com/yokk-ai/lightweight-ml",
    category: "devtools",
    tags: ["open-source", "ml", "performance", "mobile"],
    image_url: null,
    upvotes: 423,
    comment_count: 45,
    view_count: 1200,
    is_answered: false,
    is_featured: false,
    created_at: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
    profiles: demoProfiles[3],
  },
  {
    id: "post-5",
    author_id: "user-1",
    type: "discussion",
    title: "Telemedicine platform reaches 1 million consultations",
    content:
      "Excited to announce that our telemedicine platform just reached 1 million consultations! Rural healthcare access is finally improving across West Africa. The future of African healthtech is bright. 💪",
    category: "healthtech",
    tags: ["healthtech", "telemedicine", "milestone"],
    image_url: null,
    upvotes: 312,
    comment_count: 28,
    view_count: 890,
    is_answered: false,
    is_featured: false,
    created_at: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
    profiles: demoProfiles[0],
  },
  {
    id: "post-6",
    author_id: "user-2",
    type: "tutorial",
    title: "Building Africa's First Offline-First Learning Platform",
    content:
      "How we built an education platform that works with intermittent connectivity, serving 500K students across 8 countries with downloadable course content and sync-when-connected architecture.",
    category: "edtech",
    tags: ["edtech", "offline-first", "education", "pwa"],
    image_url: "/students-using-tablets-learning-africa-classroom.jpg",
    upvotes: 678,
    comment_count: 92,
    view_count: 2340,
    is_answered: false,
    is_featured: false,
    created_at: new Date(Date.now() - 8 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
    profiles: demoProfiles[1],
  },
]

// Demo products for Launch page
export const demoProducts: DemoProduct[] = [
  {
    id: "prod-1",
    name: "Cowrywise",
    tagline: "Automated savings & investments for Africa",
    description: "Save and invest in mutual funds, treasury bills, and stocks. Start with as little as ₦100.",
    logo_url: "/fintech-savings-app-logo-green.jpg",
    website_url: "https://cowrywise.com",
    category: demoCategories[1],
    maker: {
      id: demoProfiles[1].id,
      username: demoProfiles[1].username,
      full_name: demoProfiles[1].full_name,
      avatar_url: demoProfiles[1].avatar_url,
    },
    upvotes: 1456,
    comment_count: 234,
    is_featured: true,
    launched_at: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "prod-2",
    name: "Farmcrowdy",
    tagline: "Digital agriculture investment platform",
    description: "Connect with verified farms and earn returns while supporting African agriculture.",
    logo_url: "/agriculture-farm-app-logo-orange.jpg",
    website_url: "https://farmcrowdy.com",
    category: demoCategories[2],
    maker: {
      id: demoProfiles[2].id,
      username: demoProfiles[2].username,
      full_name: demoProfiles[2].full_name,
      avatar_url: demoProfiles[2].avatar_url,
    },
    upvotes: 892,
    comment_count: 156,
    is_featured: true,
    launched_at: new Date(Date.now() - 48 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "prod-3",
    name: "54gene",
    tagline: "African genomics for global health",
    description: "Building Africa's largest biobank to ensure Africans are represented in genomic research.",
    logo_url: "/biotech-dna-logo-blue.jpg",
    website_url: "https://54gene.com",
    category: demoCategories[3],
    maker: {
      id: demoProfiles[0].id,
      username: demoProfiles[0].username,
      full_name: demoProfiles[0].full_name,
      avatar_url: demoProfiles[0].avatar_url,
    },
    upvotes: 723,
    comment_count: 89,
    is_featured: false,
    launched_at: new Date(Date.now() - 72 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "prod-4",
    name: "uLesson",
    tagline: "Quality education for every African child",
    description: "K-12 learning platform with offline-first video lessons and adaptive learning paths.",
    logo_url: "/education-learning-app-logo-purple.jpg",
    website_url: "https://ulesson.com",
    category: demoCategories[4],
    maker: {
      id: demoProfiles[3].id,
      username: demoProfiles[3].username,
      full_name: demoProfiles[3].full_name,
      avatar_url: demoProfiles[3].avatar_url,
    },
    upvotes: 634,
    comment_count: 78,
    is_featured: false,
    launched_at: new Date(Date.now() - 96 * 60 * 60 * 1000).toISOString(),
  },
]

// Demo achievements for profile page
export const demoAchievements: Achievement[] = [
  {
    id: "ach-1",
    name: "First Post",
    description: "Published your first post",
    icon: "edit",
    xp_reward: 50,
    rarity: "common",
  },
  {
    id: "ach-2",
    name: "Rising Star",
    description: "Reached 100 upvotes on a single post",
    icon: "star",
    xp_reward: 100,
    rarity: "uncommon",
  },
  {
    id: "ach-3",
    name: "Community Builder",
    description: "Gained 10 followers",
    icon: "users",
    xp_reward: 150,
    rarity: "uncommon",
  },
  {
    id: "ach-4",
    name: "Voice of Africa",
    description: "Posted 5 voice comments",
    icon: "mic",
    xp_reward: 75,
    rarity: "common",
  },
  {
    id: "ach-5",
    name: "Launch Master",
    description: "Launched a product with 500+ upvotes",
    icon: "rocket",
    xp_reward: 500,
    rarity: "legendary",
  },
  {
    id: "ach-6",
    name: "Bo's Friend",
    description: "Had 50 conversations with Bo AI",
    icon: "sparkles",
    xp_reward: 200,
    rarity: "rare",
  },
]

// Demo user achievements (which ones the demo user has unlocked)
export const demoUserAchievements: UserAchievement[] = [
  { achievement_id: "ach-1", unlocked_at: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString() },
  { achievement_id: "ach-2", unlocked_at: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000).toISOString() },
  { achievement_id: "ach-4", unlocked_at: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString() },
]

// Demo user for logged-in state preview
export const demoCurrentUser: Profile & { achievements?: UserAchievement[] } = {
  id: "current-user",
  username: "yokk_dev",
  email: "dev@yokk.io",
  full_name: "YOKK Developer",
  avatar_url: "/african-developer-avatar.jpg",
  bio: "Building the future of African tech",
  website_url: null,
  github_url: "https://github.com/yokk-dev",
  twitter_url: null,
  level: 12,
  xp: 1260,
  streak_days: 5,
  last_activity_date: new Date().toISOString(),
  total_posts: 12,
  total_comments: 34,
  helpful_comments: 8,
  total_launches: 1,
  preferred_languages: ["typescript", "python"],
  interests: ["african-tech", "community"],
  created_at: new Date().toISOString(),
  updated_at: new Date().toISOString(),
  achievements: demoUserAchievements,
}
