import type { Post, Profile, Category, DemoProduct, Achievement, UserAchievement } from "@/lib/types"

// Demo categories
export const demoCategories: Category[] = [
  { id: "cat-1", name: "AI/ML", slug: "ai-ml", color: "#8B5CF6", icon: "brain" },
  { id: "cat-2", name: "FinTech", slug: "fintech", color: "#10B981", icon: "banknote" },
  { id: "cat-3", name: "AgriTech", slug: "agritech", color: "#22C55E", icon: "leaf" },
  { id: "cat-4", name: "HealthTech", slug: "healthtech", color: "#EF4444", icon: "heart" },
  { id: "cat-5", name: "EdTech", slug: "edtech", color: "#3B82F6", icon: "book" },
  { id: "cat-6", name: "CleanTech", slug: "cleantech", color: "#06B6D4", icon: "sun" },
]

// Demo profiles
export const demoProfiles: Profile[] = [
  {
    id: "user-1",
    username: "amara_nwosu",
    display_name: "Amara Nwosu",
    avatar_url: "/african-woman-developer.jpg",
    bio: "AI researcher | TechCabal contributor | Building the future of African AI",
    level: 23,
    xp: 2340,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "user-2",
    username: "kwame_asante",
    display_name: "Kwame Asante",
    avatar_url: "/african-man-tech.jpg",
    bio: "FinTech founder | Ex-Paystack | Scaling payments across Africa",
    level: 31,
    xp: 5200,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "user-3",
    username: "fatima_diallo",
    display_name: "Fatima Diallo",
    avatar_url: "/african-woman-entrepreneur.jpg",
    bio: "AgriTech innovator | Helping farmers with AI-powered solutions",
    level: 18,
    xp: 1800,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "user-4",
    username: "tunde_okonkwo",
    display_name: "Tunde Okonkwo",
    avatar_url: "/african-man-software-engineer.jpg",
    bio: "Full-stack dev | Open source contributor | Lagos tech community organizer",
    level: 27,
    xp: 3500,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
]

// Demo posts
export const demoPosts: Post[] = [
  {
    id: "post-1",
    user_id: "user-1",
    category_id: "cat-1",
    type: "article",
    title: "African AI Startups Raise $2.3B in Record Funding Round",
    content:
      "Pan-African AI companies are transforming healthcare, agriculture, and financial services across the continent with innovative machine learning solutions. This marks a turning point for tech investment in Africa.",
    image_url: "/african-tech-startup-office-team-meeting.jpg",
    video_url: null,
    read_time: 8,
    is_featured: true,
    is_fire: false,
    upvotes: 1247,
    comments_count: 89,
    created_at: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
    profiles: demoProfiles[0],
    categories: demoCategories[0],
  },
  {
    id: "post-2",
    user_id: "user-2",
    category_id: "cat-2",
    type: "article",
    title: "Nigerian FinTech Unicorn Expands to 12 African Countries",
    content:
      "Major expansion announcement as Lagos-based payment platform reaches unicorn status and announces plans to serve 100 million users by 2026.",
    image_url: "/mobile-payment-app-africa-fintech.jpg",
    video_url: null,
    read_time: 5,
    is_featured: true,
    is_fire: true,
    upvotes: 892,
    comments_count: 156,
    created_at: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
    profiles: demoProfiles[1],
    categories: demoCategories[1],
  },
  {
    id: "post-3",
    user_id: "user-3",
    category_id: "cat-3",
    type: "article",
    title: "AI-Powered Crop Disease Detection Saves Millions in Harvest",
    content:
      "New mobile app using computer vision helps smallholder farmers identify crop diseases early, preventing estimated $50M in losses across East Africa.",
    image_url: "/african-farmer-using-smartphone-in-field-agricultu.jpg",
    video_url: null,
    read_time: 6,
    is_featured: false,
    is_fire: false,
    upvotes: 534,
    comments_count: 67,
    created_at: new Date(Date.now() - 6 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
    profiles: demoProfiles[2],
    categories: demoCategories[2],
  },
  {
    id: "post-4",
    user_id: "user-4",
    category_id: "cat-1",
    type: "post",
    title: null,
    content:
      "Just shipped v2.0 of our open-source ML framework optimized for low-bandwidth environments. 60% smaller model sizes with only 3% accuracy loss. Perfect for African mobile networks! 🚀\n\nCheck it out: github.com/yokk-ai/lightweight-ml",
    image_url: null,
    video_url: null,
    read_time: null,
    is_featured: false,
    is_fire: true,
    upvotes: 423,
    comments_count: 45,
    created_at: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
    profiles: demoProfiles[3],
    categories: demoCategories[0],
  },
  {
    id: "post-5",
    user_id: "user-1",
    category_id: "cat-4",
    type: "post",
    title: null,
    content:
      "Excited to announce that our telemedicine platform just reached 1 million consultations! Rural healthcare access is finally improving across West Africa. The future of African healthtech is bright. 💪",
    image_url: null,
    video_url: null,
    read_time: null,
    is_featured: false,
    is_fire: false,
    upvotes: 312,
    comments_count: 28,
    created_at: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
    profiles: demoProfiles[0],
    categories: demoCategories[3],
  },
  {
    id: "post-6",
    user_id: "user-2",
    category_id: "cat-5",
    type: "article",
    title: "Building Africa's First Offline-First Learning Platform",
    content:
      "How we built an education platform that works with intermittent connectivity, serving 500K students across 8 countries with downloadable course content and sync-when-connected architecture.",
    image_url: "/students-using-tablets-learning-africa-classroom.jpg",
    video_url: null,
    read_time: 12,
    is_featured: false,
    is_fire: false,
    upvotes: 678,
    comments_count: 92,
    created_at: new Date(Date.now() - 8 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
    profiles: demoProfiles[1],
    categories: demoCategories[4],
  },
]

// Demo products for Launch page
export const demoProducts: DemoProduct[] = [
  {
    id: "prod-1",
    name: "Cowrywise",
    tagline: "Automated savings & investments for Africa",
    description: "Save and invest in mutual funds, treasury bills, and stocks. Start with as little as ₦100.",
    logo_url: "/fintech-savings-app-logo-green.jpg",
    website_url: "https://cowrywise.com",
    category: demoCategories[1],
    maker: demoProfiles[1],
    upvotes: 1456,
    comments_count: 234,
    is_featured: true,
    launched_at: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "prod-2",
    name: "Farmcrowdy",
    tagline: "Digital agriculture investment platform",
    description: "Connect with verified farms and earn returns while supporting African agriculture.",
    logo_url: "/agriculture-farm-app-logo-orange.jpg",
    website_url: "https://farmcrowdy.com",
    category: demoCategories[2],
    maker: demoProfiles[2],
    upvotes: 892,
    comments_count: 156,
    is_featured: true,
    launched_at: new Date(Date.now() - 48 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "prod-3",
    name: "54gene",
    tagline: "African genomics for global health",
    description: "Building Africa's largest biobank to ensure Africans are represented in genomic research.",
    logo_url: "/biotech-dna-logo-blue.jpg",
    website_url: "https://54gene.com",
    category: demoCategories[3],
    maker: demoProfiles[0],
    upvotes: 723,
    comments_count: 89,
    is_featured: false,
    launched_at: new Date(Date.now() - 72 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "prod-4",
    name: "uLesson",
    tagline: "Quality education for every African child",
    description: "K-12 learning platform with offline-first video lessons and adaptive learning paths.",
    logo_url: "/education-learning-app-logo-purple.jpg",
    website_url: "https://ulesson.com",
    category: demoCategories[4],
    maker: demoProfiles[3],
    upvotes: 634,
    comments_count: 78,
    is_featured: false,
    launched_at: new Date(Date.now() - 96 * 60 * 60 * 1000).toISOString(),
  },
]

// Demo achievements for profile page
export const demoAchievements: Achievement[] = [
  {
    id: "ach-1",
    name: "First Post",
    description: "Published your first post",
    icon: "edit",
    xp_reward: 50,
    rarity: "common" as const,
  },
  {
    id: "ach-2",
    name: "Rising Star",
    description: "Reached 100 upvotes on a single post",
    icon: "star",
    xp_reward: 100,
    rarity: "uncommon" as const,
  },
  {
    id: "ach-3",
    name: "Community Builder",
    description: "Gained 10 followers",
    icon: "users",
    xp_reward: 150,
    rarity: "uncommon" as const,
  },
  {
    id: "ach-4",
    name: "Voice of Africa",
    description: "Posted 5 voice comments",
    icon: "mic",
    xp_reward: 75,
    rarity: "common" as const,
  },
  {
    id: "ach-5",
    name: "Launch Master",
    description: "Launched a product with 500+ upvotes",
    icon: "rocket",
    xp_reward: 500,
    rarity: "legendary" as const,
  },
  {
    id: "ach-6",
    name: "Bo's Friend",
    description: "Had 50 conversations with Bo AI",
    icon: "sparkles",
    xp_reward: 200,
    rarity: "rare" as const,
  },
]

// Demo user achievements (which ones the demo user has unlocked)
export const demoUserAchievements: UserAchievement[] = [
  { achievement_id: "ach-1", unlocked_at: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString() },
  { achievement_id: "ach-2", unlocked_at: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000).toISOString() },
  { achievement_id: "ach-4", unlocked_at: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString() },
]

// Demo user for logged-in state preview
export const demoCurrentUser: Profile & { achievements?: UserAchievement[] } = {
  id: "current-user",
  username: "yokk_dev",
  display_name: "YOKK Developer",
  avatar_url: "/african-developer-avatar.jpg",
  bio: "Building the future of African tech",
  level: 12,
  xp: 1260,
  created_at: new Date().toISOString(),
  updated_at: new Date().toISOString(),
  achievements: demoUserAchievements,
}
